In [ ]:
a=1
b=1
c=1
a+b+c

In [ ]:
1a=1

In [ ]:
a 1=1


In [ ]:
a_1=1


In [ ]:
_a=1

In [ ]:
_a1=1


 __a=1

In [ ]:
__a=1


In [ ]:
a@gmail.com=1

In [ ]:
if=2

In [ ]:
a=1
type(a)

In [ ]:
count = 100         #integer assingment 
kilometer = 1000.0  #floot assignmente
name = "rushvik" 

In [ ]:
print(count, kilometer,name )

In [ ]:
a,b,c=1,2,"Rushvik"
print(a,b,c)

In [ ]:
a=b=c=1
print(a,b,c)

In [ ]:
print(id(a))
print(id(b))
print(id(c))


In [ ]:
a=1
b=1
c=1
print(id(a))
print(id(b))
print(id(c))


In [ ]:
a

In [ ]:
del a

In [ ]:
a

In [ ]:
d=3.13j

In [ ]:
type(d)

In [ ]:
str1="python is language "
print(str1)

In [ ]:
a=6746
a*2

In [ ]:
str1="Python is a programming language"
print(str1* 2
     )

In [ ]:
str2='H
1'
print(str1+str2)

In [ ]:
a=2
print(id(a))

In [ ]:
a=1
print(id(a))


In [ ]:
a=[2,3]
print(a[1])

In [ ]:
a=1
print(id(a))
b=2
print(id(b))


In [ ]:
print(str1)

In [ ]:
print(str1[2:10])

In [ ]:
print(str1[6:18])

In [ ]:
print(str1)

In [ ]:
str2 = "Python is a programming Language"

In [ ]:
print(str2)

In [ ]:
print("12:23")

In [ ]:
print(str2[12:23])

In [ ]:
str2.upper()

In [ ]:
str2.split()

In [ ]:
str3="{0} {2} {1}".format("python", "java", "clang")
print(str3)


In [ ]:
str3="{a} {b} {c}".format(a="I", b="am", c="Good")
print(str3)

In [ ]:
str3="{c} {a} {b}".format(a="I", b="am", c="Good")
print(str3)

# List

In [ ]:
#list
l=[1, 2, 3,'abc', 12.5]
print(l[3][2])


In [ ]:
ks=[1,2,3]
ks+ks

In [ ]:
ps=[12,34,55]
ps+ks

In [ ]:

ls2=[1,2,3]
ls2*3




 

In [ ]:
i


In [ ]:
l

In [ ]:
l[0]=10

In [ ]:
l

In [ ]:
print(id(l[0]))

In [ ]:
print(id(l))

In [ ]:
print(id(l[1]))

In [ ]:
l[1]=4

In [ ]:
print(id(l[1]))

In [ ]:
l2="rushvik"
print(id(l2))

In [ ]:
id(l2[1])

In [ ]:
l2="n"+l2[1:]
l2

In [ ]:
id(l2[1])

In [ ]:
id(l2)

In [ ]:
a=int(input("Enter Your age "))


In [ ]:
a

In [ ]:
type(a)

In [ ]:
a*2

In [ ]:
a=input("enter sequence: ")

In [ ]:
a

# Tuple


In [ ]:
#Tuple
tuple1 = ('abcd', 786, 7.4, "john",80.2)

In [ ]:
tuple1

In [ ]:
tuple1[0]

In [ ]:
tuple1[1]='hi'

In [ ]:
tuple1*4

# Dictionary

In [ ]:
dict1 = {}

In [ ]:
dict1

In [ ]:
dict1['one'] = "this is Python"

In [ ]:
dict1

In [ ]:
type(dict1)

In [ ]:
dict1['one'] = "this is Python"
dict1[2] = "this is java"


In [ ]:
dict1

In [ ]:
dict2 = {
    'name':'rohit',
    'id': 1234,
    'dept': 'IT'
}

In [ ]:
dict2

In [ ]:
dict2['name']

In [ ]:
dict2['id']

In [ ]:
dict2['dept']

In [ ]:
print(dict2.keys())

# While Loop

In [ ]:
num=0
while(num<10):
    print(num)
    num+=1

In [ ]:
while(count < 5):
    print(count, " is less than 5")
    count +=1
else:
    print(count, " is not less than 5")

# For Loop

In [ ]:
a= [1,2,3,4,5]
for i in a:
    print(i)

In [ ]:
a = input(" enter your name")

In [ ]:
total = 0
for i in a:
    print(i)
    total+=1
    
print(total)

# Numpy

In [ ]:
a=[2,3]
a*2

In [1]:
import numpy as np 

In [ ]:
a*2

In [2]:
!pip install numpy

In [4]:
a_n=np.array(a)


NameError: name 'a' is not defined

In [ ]:
a_n

In [ ]:
a_n*2

In [ ]:
marks=[23,20,15,18,27,21,12,14,29,30]
marks=np.array(marks)

In [ ]:
np.mean(marks)

In [ ]:
np.amin(marks)

In [ ]:
np.amax(marks)

In [ ]:
np.mean(marks)

In [ ]:
np.median(marks)

In [ ]:
np.ptp(marks)

In [ ]:
np.std(marks)

In [ ]:
np.var(marks)

In [ ]:
np.average(marks)

In [ ]:
x=[34,45,56,64]
x_n=np.array(x)
print(np.std(x_n))

In [ ]:
ss=np.mean((x_n-np.mean(x_n))**2)

In [ ]:
ss

In [ ]:
np.sqrt(ss)

In [8]:
from numpy import random

In [ ]:
int(random.rand()*10)

In [ ]:
 x=2.75

In [ ]:
x=1+(1-3.5)*x

In [9]:
random.seed(12)
for i in range(10):
    print(random.rand())

0.15416284237967237
0.7400496965154048
0.26331501518513467
0.5337393933802977
0.014574962485419674
0.918747008099885
0.9007148541170122
0.03342142762634459
0.9569493362751168
0.13720932135607644


In [10]:
b= [1, 3, 4]
b[2]

4

In [12]:
c = [[1,2],[3,4]]
c[1][0]

3

In [17]:
import numpy as np 
c_n=np.array(c)

In [18]:
c_n

array([[1, 2],
       [3, 4]])

In [19]:
c_n.dtype

dtype('int32')

In [20]:
c_n.strides

(8, 4)

In [21]:
c_n+1

array([[2, 3],
       [4, 5]])

In [22]:
c_n.shape

(2, 2)

In [23]:
d_n=np.array([1])

In [24]:
d_n.shape

(1,)

In [25]:
import numpy as np

In [36]:
a=np.loadtxt("https://raw.githubusercontent.com/goradbj/MachineLearning/main/cric.tsv",skiprows=1)

In [46]:
dravid_runs=a[:,2]
np.mean(dravid_runs)

71.06666666666666

In [44]:
sachin_runs=a[:,1]
np.mean(sachin_runs)

63.6

In [47]:
india_runs=a[:,3]
np.mean(india_runs)

281.26666666666665

In [48]:
np.corrcoef(dravid_runs,india_runs)

array([[1.        , 0.44853003],
       [0.44853003, 1.        ]])

In [49]:
np.corrcoef(sachin_runs,india_runs)

array([[1.        , 0.70460106],
       [0.70460106, 1.        ]])